### ISSUE TITLE
Sodiumoxide is no longer maintained (and not wasm-friendly)

### ISSUE THREAD

**Issue by m-kus** [airgap-it/tezos-rust-sdk#3]
Hey!

Have recently noticed that https://github.com/sodiumoxide/sodiumoxide is no longer maintained, as an alternative there is https://github.com/dalek-cryptography/ed25519-dalek

I was able to implement a custom crypto provider with it (thanks to the flexible configuration interface) and verifier worked with no issues, although signer has not passed the tests, might be something with deterministic signature options.

If you'd like, I can make a PR for replacing the default provider, or make it feature-enabled.

**Comment by RomarQ** [comment]
Thanks for raising the deprecation issue.

Hopefully, we will have some time next week to look into it. Also, feel free to submit a PR.

**Comment by RomarQ** [comment]
`sodiumoxide` has been replaced with `ed25519-dalek` in https://github.com/airgap-it/tezos-rust-sdk/commit/4af9859fb6be60028a7899723a3c9885cb834094

Thanks for the remark :+1:
